version: 1

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64

archives:
  - format: tar.gz

brews:
  - name: bash-generator
    description: "Generate Bash commands by saying what you want"
    homepage: "https://github.com/jerilseb/bash-generator"
    repository:
      owner: jerilseb
      name: homebrew-tap
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com