version: 1

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - format: tar.gz
    format_overrides:
    - goos: windows
      format: zip

brews:
  - name: aibash
    description: "Generate Bash commands by saying what you want"
    homepage: "https://github.com/jerilseb/aibash"
    repository:
      owner: jerilseb
      name: homebrew-tap
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com